config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users  
  resources :authors
  resources :tags
  resources :categories
  resources :articles
  resources :issues

  root 'home#index'
  

end

app/models/ability.rb
class Ability
include CanCan::Ability
  def initialize(user)
    user ||= User.new

    # Admin
    if user.role_id == 4
      can :manage, :all
    else
      # Editor
      if user.role_id == 3
        can :manage, :all 
    else
      # Contributor
      if user.role_id == 2
        can :manage, :all 
    else
      # Subscriber (default)
      if user.role_id == 1
        can :read, Article 
        can :read, Issue
      end
      end
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  translates :title, :introduction, :body
  has_and_belongs_to_many :issues
  has_many :categories
  has_many :tags
  mount_uploader :article_feature, ArticleFeatureUploader
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :article
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  translates :title, :introduction, :summary
  has_and_belongs_to_many :articles
  mount_uploader :issue_feature, IssueFeatureUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  before_create :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('subscriber')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.all 
  end

  # GET /articles/new
  def new
    @article = Article.new    
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @issue = Issue.find(params[:article][:issue_id])
    @article = @issue.articles.create!(article_params)    

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }

      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :introduction, :author, :article_lan, :article_feature, :body, :issue_id, :Category, :tags, :commit, :published)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :username)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.order('created_at desc')
    @issues = Issue.order('created_at desc')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :create, :update, :destroy]

  load_and_authorize_resource

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issues = Issue.all
    @articles = Issue.find(params[:id]).articles
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create    

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      # @issue = Issue.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :issue_feature, :language, :introduction, :summary)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/articles_issues_helper.rb
module ArticlesIssuesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

<%= render :partial => 'layouts/article.navigation', :locals => { :f => f} %>

<!-- Navigation Partial -->

<div class="clearfix"> 
  
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <div class="large-12 columns alpha beta"> 

    <div class="container">
    
    

      <% if @article.article_feature_url.to_s.length > 0 %>
      
        <div class="post-intro  clearfix">       
          <div class="post row">    
            <div class="post-image small-12 columns alpha beta">
            <%= image_tag @article.article_feature_url.to_s, class: "lazy post-image", id: "article_article_feature" %>
            </div>
          </div>
        </div>        
        
        <div class="post row"> 
          <h4 class="post-image-upload"><%= (t('upload_image')) %></h4>
          <%= f.file_field :article_feature %>
        </div>

      <% end %>


        <% if @article.article_feature_url.to_s.length == 0 %>
                  
          <div class="post row"> 
            <h4 class="post-image-upload"><%= (t('upload_image')) %></h4>
            <%= f.file_field :article_feature %>
          </div>

        <% end %>

        <div class="row post-content">
        <div class="post-body small-12 medium-7 large-7 medium-offset-1 large-offset-0 columns alpha beta right">
          
          <div class="show-for-small-only">
            <%= f.text_area :title, rows: 20, class: "post-title-input", placeholder: (t('title')) %>
            <%= f.text_area :introduction, rows: 8, class: "post-teaser-input", placeholder: (t('summary')) %>
          </div>
          
          <%= f.cktext_area :body, rows: 100, class: "post-content-input", placeholder: "Article content" %>

       

        </div>
        <div class="post-related medium-4 left beta alpha">
          <div class="show-for-medium-up" id="addarticle">
            
            <h5 class="post-issue-select">
              <%= (t('select_language')) %>
            </h5>
            <div class="post-language-select">
              <% if I18n.locale != :en %>
               <%= link_to "中文", {locale: 'zh-CN'}, :class => 'selected_lan' %>
               <%= link_to "EN", {locale: 'en'}, :class => 'unselected_lan' %>
              <% end %>
              <% if I18n.locale == :en %>
               <%= link_to "中文", {locale: 'zh-CN'}, :class => 'unselected_lan' %>
               <%= link_to "EN", {locale: 'en'}, :class => 'selected_lan' %>             
              <% end %>
            </div>

            <%= f.text_area :title, rows: 20, class: "post-title-input", placeholder: (t('title')) %>
            <%= f.text_area :introduction, rows: 8, class: "post-teaser-input", placeholder: (t('summary')) %>
            
            <h5 class="post-issue-select">
              <%= (t('select_issue')) %>
            </h5>
            <%= f.collection_select(:issue_id, Issue.all, :id, :title) %>
            <% if current_user.role_id >= 2 %>
              <%= link_to (t('delete')), @article, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'small button alert' %>
            <% end %>          

          </div>
        </div>
          <div class="post-buttons small-12 columns beta">
            <%= f.submit (t('save')), class: 'button small' %>
          </div> 
        </div>        

     <% end %>

    </div> 

  </div>

</div>

app/views/articles/create.js.erb
$("#post-image").append("<%= j render(@article) %>");

app/views/articles/index.html.erb
        <ul class="medium-block-grid-2 large-block-grid-3 issue-index-list">
          <% @articles.with_translations(I18n.locale).each do |article| %>          
            <li class="issue-index-article">
              <%= image_tag article.article_feature_url.to_s, class: "lazy issue-index-article-thumbnail" %>
              <div class="issue-index-article-body">
                <%=link_to article.title, article, class: "issue-index-article-title"%>

                
                <div class="article-index-status">
                  <% if article.published == true %>
                    <h5 class="article-index-status-published">
                      <%= (t('published_in'))%>
                    </h5>
                    <h5 class="article-index-status-issue"><%= Article.find(article.id).issues.find(article.issue_id).title %></h5>
                    <% else %>
                    <h5 class="article-index-status-unpublished">
                      Unpublished
                    </h5>
                  <% end %>                  
                </div>

                <p class="issue-index-article-teaser"><%= article.introduction %></p>
                <% if current_user.role_id >= 2 %>
                  <%= link_to (t('edit')), edit_article_path(article), :class => 'small button edit' %>
                <% end %>
                <% if current_user.role_id >= 2 %>
                  <%= link_to (t('delete')), article, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'small button alert' %>
                <% end %>            

              </div>
              </a>
            </li>          
            <% end %>
          </ul>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="clearfix">       
  <div class="large-12 columns alpha beta"> 
  <div class="container">
    <div class="post-intro  clearfix"> 
      <div class="post row">    
        <div class="post-image small-12 columns alpha beta">
        <%= image_tag @article.article_feature_url.to_s, class: "lazy post-image" %>
        </div>
      </div>
    </div>
    <div class="row post-content">
      <div class="post-body small-12 medium-7 large-7 medium-offset-1 large-offset-0 columns alpha beta right">      
      <div class="show-for-small-only">
        <h1 class="post-title"><%= @article.title %></h1>        
        <p class="post-teaser"><%= @article.introduction %></p>
      </div>
      <%= raw(@article.body) %>
      </div>
      <div class="post-related medium-4 left beta alpha">
        <div class="show-for-medium-up">
          <h1 class="post-title"><%= @article.title %></h1>        
          <p class="post-teaser"><%= @article.introduction %></p>
          <div class="post-actions">
            <% if current_user.role_id >= 2 %>
              <%= link_to (t('edit')), edit_article_path(@article), :class => 'small button edit' %>
            <% end %>
            <% if current_user.role_id >= 2 %>
              <%= link_to (t('delete')), @article, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'small button alert' %>
            <% end %>
          </div>
        </div>
        <div class="post-meta small-12 columns alpha beta end">
          <div class="post-related-list">
            <ul class="post-related-articles medium-8 columns alpha">
              <% @articles.with_translations(I18n.locale).each do |article|%>
              <% if article.title != @article.title %>
              <%= link_to(article) do %>
              <li class="post-related-list-item">
                <%= image_tag article.article_feature_url.to_s, class: "lazy issue-index-article-thumbnail" %>
                <h4 class="post-related-list-item-title">
                  <%= article.title%>             
                </h4>
              </li>
              <% end %>
              <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div> 
  </div>
</div>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= author.username %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>

<%= render :partial => 'layouts/issue.navigation', :locals => { :f => f} %>

<div class="clearfix"> 
  
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  

  <div class="large-12 columns alpha beta"> 

    <div class="container">
    
    

      <% if @issue.issue_feature_url.to_s.length > 0 %>
      
        <div class="post-intro  clearfix">       
          <div class="post row">    
            <div class="post-image small-12 columns alpha beta">
            <%= image_tag @issue.issue_feature_url.to_s, class: "lazy post-image", id: "issue_issue_feature" %>
            </div>
          </div>
        </div>        
        
        <div class="post row"> 
          <h4 class="post-image-upload"><%= (t('upload_image')) %></h4>
          <%= f.file_field :issue_feature %>
        </div>

      <% end %>


        <% if @issue.issue_feature_url.to_s.length == 0 %>
                  
          <div class="post row"> 
            <h4 class="post-image-upload"><%= (t('upload_image')) %></h4>
            <%= f.file_field :issue_feature %>
          </div>

        <% end %>

        <div class="row post-content">
        <div class="post-body small-12 medium-7 large-7 medium-offset-1 large-offset-0 columns alpha beta right">
          
          <div class="show-for-small-only">
            <%= f.text_field :title, class: "post-title-input", placeholder: "Issue Title" %>
            <%= f.text_field :summary, class: "post-teaser-input", placeholder: "Issue Teaser" %>
            <div class="post-meta small-12 columns">
              <h4>Article Meta Data</h4>
              <select name="Issue" id="issue-select" class="small-12 medium-3 columns left">
                <option value="" default selected>Issue</option>
              </select>
              <select name="Category" id="category-select" class="small-12 medium-3 columns left">
                <option value="" default selected>Category</option>
              </select>
              <div class="small-12 medium-4 left">          
                <input type="text" placeholder="tag1, tag2, tag3" ng-model="newIssue.tags" name="tags" class="post-tags-input">
              </div>
            </div>
          </div>
          
          <%= f.cktext_area :introduction, rows: 60, class: "post-content-input", placeholder: "Issue introduction" %>

          <div class="post-buttons small-12 columns beta">
            <%= f.submit (t('save')), class: 'button small' %>
          </div>        

        </div>
        <div class="post-related medium-4 left beta alpha">
          <div class="show-for-medium-up" id="addarticle">
            <%= f.text_area :title, rows: 20, class: "post-title-input", placeholder: (t('title')) %>
            <%= f.text_area :summary, rows: 8, class: "post-teaser-input", placeholder: (t('summary')) %>
          
          </div>
        </div>
        </div>

     <% end %>
    
    </div> 

  </div>

</div>

app/views/issues/edit.html.erb
<%= render 'form' %>

app/views/issues/index.html.erb
<h1>Listing issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Feature image</th>
      <th>Language</th>
      <th>Introduction</th>
      <th>Summary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.feature_image %></td>
        <td><%= issue.introduction %></td>
        <td><%= issue.summary %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<%= render 'form' %>

app/views/issues/show.html.erb
<div class="clearfix">       
  <div class="large-12 columns alpha beta"> 
  <div class="container">
    <div class="post-intro  clearfix"> 
      <div class="post row">    
        <div class="post-image small-12 columns alpha beta">
        <%= image_tag @issue.issue_feature_url.to_s, class: "lazy post-image" %>
        </div>
      </div>
    </div>
    <div class="row post-content">
      <div class="post-body small-12 medium-7 large-7 medium-offset-1 large-offset-0 columns alpha beta right">      
      <div class="show-for-small-only">
        <h1 class="post-title"><%= @issue.title %></h1>        
      </div>
      <%= raw(@issue.introduction) %>
      </div>
      <div class="post-related medium-4 left beta alpha">
        <div class="show-for-medium-up">
          <h1 class="post-title"><%= @issue.title %></h1>        
          <div class="post-actions">
            <% if current_user.role_id >= 2 %>
              <%= link_to (t('edit')), edit_issue_path(@issue), :class => 'small button edit' %>
            <% end %>
            <% if current_user.role_id >= 3 %>
              <%= link_to (t('delete')), @issue, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'small button alert' %>
            <% end %>
          </div>
          <ul class="post-related-list small-12 medium-8 columns alpha">
            <% @articles.with_translations(I18n.locale).each do |article| %>
            <%= link_to(article) do %>
            <li class="post-related-list-item">
              <%= image_tag article.article_feature_url.to_s %> 
              <h4 class="post-related-list-item-title">
                <%= article.title%>             
              </h4>
            </li>
            <% end %>
            </a>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div> 
  </div>
</div>