config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users  
  resources :authors
  resources :tags
  resources :categories
  resources :articles
  resources :issues

  root 'home#index'
  

end

app/models/ability.rb
class Ability
include CanCan::Ability
  def initialize(user)
    user ||= User.new

    # Admin
    if user.role_id == 4
      can :manage, :all
    else
      # Editor
      if user.role_id == 3
        can :manage, :all 
    else
      # Contributor
      if user.role_id == 2
        can :manage, :all 
    else
      # Subscriber (default)
      if user.role_id == 1
        can :read, Article 
        can :read, Issue
      end
      end
      end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  translates :title, :introduction, :body
  has_and_belongs_to_many :issues
  has_many :categories
  has_many :tags
  mount_uploader :article_feature, ArticleFeatureUploader
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :article
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  translates :title, :introduction, :summary
  has_and_belongs_to_many :articles
  mount_uploader :issue_feature, IssueFeatureUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :role
  before_create :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('subscriber')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.order('created_at desc')
    @issues = Issue.order('created_at desc')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :create, :update, :destroy]

  load_and_authorize_resource

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issues = Issue.all
    @articles = Issue.find(params[:id]).articles
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create    

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      # @issue = Issue.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :issue_feature, :language, :introduction, :summary)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_article.navigation.html.erb
<!-- Navigation Partial -->
<div class="navigation fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <a href="/">
        <%= link_to root_path :locale do %>
          <%= image_tag "branding.png" %>            
          <h1 class="branding-title"><span class="bold">Octave</span> journal</h1>
        <% end %>
      </li>
    </ul>
    <section class="top-bar-section">
      
      <!-- Right Nav Section -->
      <ul class="right">
        
        <% if user_signed_in? && params[:controller] != 'articles' %>
          <% if current_user.role_id >= 2 %>
            <li class="has-form"><%= link_to (t('new_article')), new_article_path, :class => 'button' %> <%= params[:controller] %></li>
          <% end %>
          <% if current_user.role_id >= 4 %>
            <li class="has-form"><%= link_to (t('new_issue')), new_issue_path, :class => 'button' %></li> 
            <li class="has-dropdown not-click"> 
              <a href="#">Issues</a>
              <ul class="dropdown">
                <% Issue.all.each do |issue| %>
                  <li><%= link_to issue.title, issue %></li>
                <% end %>
              </ul>
            </li>
          <% end %>             
        <% end %>

        <% if user_signed_in? && params[:controller] == 'articles'%>
          <% if current_user.role_id >= 2 %>
            <% if @article.title != nil %>
            <li class="editing-message"> 
              <p>
                <%= (t('edit')) %>: <span class="editing-message-title"><%=@article.title%></span>
              </p>
            </li>
            <% end %>
            <li class="publish-switch-label">
              <p><%= (t('published'))%></p>
            </li>
            <li>              
              <div class="publish switch small">              
                <%= f.check_box :published, { id: 'publish-switch' }, "true", "false" %>
                <label for="publish-switch"><%=(t('published'))%></label>
              </div> 
            </li>
            <li class="has-form">
              <%=f.submit (t('save')), class: 'button' %>
            </li>
          <% end %>
          <% if current_user.role_id >= 4 %>
            <li class="has-form">
              <%= link_to (t('new_issue')), new_issue_path, :class => 'button' %>
            </li> 
          <% end %>             
        <% end %>
      

      </ul>

      <!-- Left Nav Section -->
    </section>
  </nav>
</div>

app/views/layouts/_issue.navigation.html.erb
<!-- Navigation Partial -->
<div class="navigation fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <a href="/">
        <%= link_to root_path :locale do %>
          <%= image_tag "branding.png" %>            
          <h1 class="branding-title"><span class="bold">Octave</span> journal</h1>
        <% end %>
      </li>
    </ul>
    <section class="top-bar-section">
      
      <!-- Right Nav Section -->
      <ul class="right">         
        <% if user_signed_in? && params[:controller] != 'issues' %>

          <% if current_user.role_id >= 2 %>
            <li class="has-form"><%= link_to (t('new_article')), new_article_path, :class => 'button' %> <%= params[:controller] %></li>
          <% end %>
          <% if current_user.role_id >= 4 %>
            <li class="has-form"><%= link_to (t('new_issue')), new_issue_path, :class => 'button' %></li> 
            <li class="has-dropdown not-click"> 
              <a href="#">Issues</a>
              <ul class="dropdown">
                <% Issue.all.each do |issue| %>
                  <li><%= link_to issue.title, issue %></li>
                <% end %>
              </ul>
            </li>
          <% end %>             
        <% end %>

        <% if user_signed_in? && params[:controller] == 'issues'%>
          <% if current_user.role_id >= 2 %>
            <% if @issue.title != nil %>
            <li class="editing-message"> 
              <p>
                <%= (t('edit')) %>: <span class="editing-message-title"><%=@issue.title%></span>
              </p>
            </li>
            <% end %>
            <li class="publish-switch-label">
              <p>Published</p>
            </li>
            <li>              
              <div class="publish switch small">              
                <%= f.check_box :published, { id: 'publish-switch' }, "true", "false" %>
                <label for="publish-switch">Publish</label>
              </div> 
            </li>
            <li class="has-form">
              <%=f.submit (t('save')), class: 'button' %>
            </li>
          <% end %>
          <% if current_user.role_id >= 4 %>
            <li class="has-form">
              <%= link_to (t('new_issue')), new_issue_path, :class => 'button' %>
            </li> 
          <% end %>             
        <% end %>


        <% if I18n.locale != :en %>
          <li><%= link_to "EN", locale: 'en' %></li>
        <% end %>
        <% if I18n.locale == :en %>
          <li><%= link_to "中文", locale: 'zh-CN'  %></li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
    </section>
  </nav>
</div>

app/views/layouts/_navigation.html.erb
<!-- Navigation Partial -->

<div class="navigation fixed">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <a href="/">
        <%= link_to root_path :locale do %>
          <%= image_tag "branding.png" %>            
          <h1 class="branding-title"><%= (t('octave_journal')) %></h1>
        <% end %>        
      </li>
      <li class="language-selection show-for-small-only">
        <% if I18n.locale != :en %>
          <div><%= link_to "EN", locale: 'en' %></div>
        <% end %>
        <% if I18n.locale == :en %>
          <div><%= link_to "中文", locale: 'zh-CN'  %></div>
        <% end %>
      </li>
    </ul>
    <section class="top-bar-section">

      <!-- Right Nav Section -->
      <ul class="right">
      <% if user_signed_in? %>
        <li>
        <%= link_to (t('logout')), destroy_user_session_path, :method => :delete %>        
        </li>
      <% else %>
        <li>
        <%= link_to (t('login')), new_user_session_path  %>  
        </li>
      <% end %>
        <% if user_signed_in? %>
          <% if current_user.role_id >= 2 %>
            <li class="has-form"><%= link_to (t('new_article')), new_article_path, :class => 'button' %></li>
            <li class="has-form"><%= link_to (t('articles')), articles_path, :class =>'button' %></li>
          <% end %>
          <% if current_user.role_id >= 4 %>
            <li class="has-form"><%= link_to (t('new_issue')), new_issue_path, :class => 'button' %></li> 
            <% end %>
            <li class="has-dropdown not-click"> 
              <a href="#" class="issues-menu"><%= (t('issues')) %></a>
              <ul class="dropdown">
                <% Issue.all.each do |issue| %>
                  <li><%= link_to issue.title, issue %></li>
                <% end %>
              </ul>
            </li>
        <% end %>

        <% if I18n.locale != :en %>
          <li><%= link_to "EN", locale: 'en' %></li>
        <% end %>
        <% if I18n.locale == :en %>
          <li><%= link_to "中文", locale: 'zh-CN'  %></li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : (t('octave_journal')) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <script src="//s3.amazonaws.com/nwapi/nwmatcher/nwmatcher-1.2.5-min.js"></script>
    <script src="//html5base.googlecode.com/svn-history/r38/trunk/js/selectivizr-1.0.3b.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.1.0/respond.min.js"></script>
  <![endif]-->
  </head>

  <body>
  
  <% if params[:action] != 'edit' && params[:action] != 'new' %>
    <%= render 'layouts/navigation' %>    
  <% end %>

    <% if flash[:error] %>
      <p class="alert alert-danger"><%= flash[:error] %></p>
    <% end %>
  
    <%= yield %>

  <% if user_signed_in? %>
    <%= render 'layouts/footer' %>
  <% end %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>    
  <%= javascript_include_tag 'data-turbolinks-track' => true %>
  </body>
</html>